### ISSUE TITLE
OPERATION PROFITABLE-FRAGMENTATION

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/security#1]
To be declassified by 4/20/2022.

**Comment by mrnerdhair** [comment]
@0xean Security would like to set up a 500 FOX bounty for this, reserved for @NeOMakinG

**Comment by 0xean** [comment]
Will do, please use the "Needs-Bounty" label in the future and add to the engineering dashboard, that way I will see these.

**Comment by mrnerdhair** [comment]
roger; ty for making the label

**Comment by 0xean** [comment]
@mrnerdhair - can you confirm this is ready to be paid out?

**Comment by mrnerdhair** [comment]
Yep!

**Comment by 0xean** [comment]
👍
