### ISSUE TITLE
Implement alerts for the DAO's reality.eth plugin

### ISSUE THREAD

**Issue by willyogo** [shapeshift/security#40]
Whenever a proposal is submitted to the ShapeShift DAO Gnosis Safe's Reality.eth plugin, an alert should be posted to the #treasury channel in Discord.

inspiration: https://twitter.com/isaacpatka/status/1530245347221577728?s=20&t=YnTGmmC9H3hWJkw9nvHXzA

AC:
1. Whenever a proposal is submitted to [ShapeShift DAO Gnosis Safe's Reality.eth plugin](https://etherscan.io/address/0xAf2D760E28Cff61447135714e6b90fA3079396e5), an alert is posted in #treasury, ie "Proposal submitted to Reality module." ; if possible, link directly to the question on Reality's app ([example](https://reality.eth.link/app/#!/question/0x5b7dd1e86623548af054a4985f7fc8ccbb554e2c-0x73fa82888c1c00c001309b792881a300b04516fc770e7e0aeb130331742c6cb4))
2. Set up two separate reporting solutions (ie. Tenderly and OZ Defender) for redundancy

**Comment by mrnerdhair** [comment]
Done; ref https://defender.openzeppelin.com/#/sentinel/10eb8b4c-e34d-4f21-890e-a52f42373f05
